avatar: /images/head/head.jpg # ç½‘ç«™ Logo
background: # æ—¢æ˜¯åšå®¢çš„èƒŒæ™¯ï¼Œåˆæ˜¯æ–‡ç« é»˜è®¤å¤´å›¾
  path: /images/background/xiaomai.jpg # èƒŒæ™¯å›¾ç‰‡è·¯å¾„
  width: 1280
  height: 726
tagsCovers: # æ–‡ç« æ ‡ç­¾è‡ªåŠ¨åŒ¹é…å°é¢å›¾
  es6: /images/post/es6.jpg
  JavaScript: /images/post/JavaScript.jpg
  TypeScript: /images/post/TypeScript.jpg
  css: /images/post/css.jpg
  node: /images/post/nodejs.jpg
  vue: /images/post/vue.jpg
  webpack: /images/post/webpack.jpg
  git: /images/post/git.jpg
  java: /images/post/java.jpg
  echarts: /images/post/echarts.jpg
  å¾®ä¿¡å°ç¨‹åº: /images/post/wechat_applet.jpg
  æµè§ˆå™¨: /images/post/browser.jpg
  ç®—æ³•: /images/post/algorithm.jpg
  æ•°æ®ç»“æ„: /images/post/data.jpg
  å·¥å…·: /images/post/editor.jpg
  UIåº“: /images/post/ui.jpg
  ç¾åŒ–: /images/post/beautify.jpg
  vite: /images/post/vite.jpg
favicon:
  href: /images/head/head.png # ç½‘ç«™å›¾æ ‡
  type: image/png # å›¾æ ‡ç±»å‹ï¼Œå¯èƒ½çš„å€¼æœ‰(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # åŠŸèƒ½å¼€å…³ï¼Œå¯é€‰å€¼ï¼ˆtrue,falseï¼‰
  globalToc: true # å¼€å¯è¯¥åŠŸèƒ½ä¼šè‡ªåŠ¨å¼€å¯æ–‡ç«  TOCï¼ˆæ–‡ç« ç›®å½•ï¼‰ åŠŸèƒ½
  wordCount: false # æ˜¯å¦å¼€å¯æ–‡ç« å­—æ•°ç»Ÿè®¡ (true, false)
  copyCode: true # æ˜¯å¦å…è®¸å¤åˆ¶ä»£ç å—

imageCDN: # å›¾ç‰‡ CDN åŠŸèƒ½
  enable: false # å¼€å¯è¯¥åŠŸèƒ½
  origin: /../../images/ # å›¾ç‰‡åŸå§‹ç›®å½•
  to: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/ # å›¾ç‰‡ CDN åŸŸå

# è‡ªå®šä¹‰æ ·å¼ï¼Œå¯ç”¨åå¯åœ¨ç«™ç‚¹çš„sourceæ–‡ä»¶å¤¹ä¸‹æ–°å»ºcustom.cssè‡ªå®šä¹‰ç«™ç‚¹æ ·å¼
customStyles:
  - custom.css

# é™„åŠ å›¾æ ‡åº“ ä½¿ç”¨è¯´æ˜ï¼šhttps://docs.nexmoe.com/config/icon
iconlib: //at.alicdn.com/t/font_2421060_8z08qcz5sq3.css # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

menu:
  å›åˆ°é¦–é¡µ:
    - /
    - icon-meishi
  æ–‡ç« å½’æ¡£:
    - /archives.html
    - icon-hanbao1
  å…³äºç³–ç³–:
    - /about.html
    - icon-jiubei1
  æˆ‘çš„æœ‹å‹:
    - /friend.html
    - icon-cola
#  ä¸‹è½½ä¸­å¿ƒ:
#    - /download.html
#    - icon-tangguo

widgets:
  - name: search
    enable: true
    options:
      search:
        type: engine # å¯é€‰engineï¼ˆç”¨æœç´¢å¼•æ“æœç´¢ï¼‰ã€swiftypeã€æˆ–localï¼ˆæœ¬åœ°æœç´¢ï¼‰
        url: https://cn.bing.com/search?q=site:tangyuxian.com # æœç´¢å¼•æ“åœ°å€ï¼Œåœ¨typeä¸ºswiftypeæ—¶æ— æ•ˆ e.g:https://www.google.com/search?q={ä½ çš„åšå®¢é“¾æ¥}
        id: <swiftype-id> # swiftypeçš„idï¼Œè§å¯ç”¨æ•™ç¨‹ã€‚åœ¨typeä¸ºengineæ—¶æ— æ•ˆ
  - name: social
    enable: true
    options:
      social:
        QQ:
          - http://wpa.qq.com/msgrd?v=3&uin=2120252100&site=qq&menu=yes
          - icon-QQ
          - rgb(64, 196, 255)
          - rgba(64, 196, 255, .1)
        mail:
          - mailto:tangyuxian@vip.qq.com
          - icon-mail-fill
          - rgb(249,8,8)
          - rgba(249,8,8,.1)
        CSDN:
          - https://blog.csdn.net/qq_40621378?type=blog
          - icon-csdn
          - rgb(199,29,35)
          - rgba(199,29,35,.1)
        åšå®¢å›­:
          - https://www.cnblogs.com/lovetangyuxian/
          - icon-bokeyuan
          - rgb(66, 214, 29)
          - rgba(66, 214, 29, .1)
        GitHub:
          - https://github.com/tangyuxian/
          - icon-github
          - rgb(25, 23, 23)
          - rgba(25, 23, 23, .15)
        gitee:
          - https://gitee.com/tangyuxian
          - icon-mayun
          - rgb(255, 255, 255)
          - rgb(199,29,35)
  - name: category
    enable: true
  - name: tagcloud
    enable: true
    options:
      maxTagcloud: 17  # æ ‡ç­¾äº‘ç»„ä»¶æ˜¾ç¤ºçš„æ ‡ç­¾æ•°é‡ï¼Œ0 è¡¨ç¤ºä¸é™åˆ¶
  - name: hitokoto # ä¸€è¨€ widget
    enable: false
    options:
      widgetHitokoto: # ä¸€è¨€ç»„ä»¶
        loading_placeholder: 'ğŸš€ è·å–ä¸­...' # æ­£åœ¨ä¸€è¨€æ—¶çš„å ä½ç¬¦
        loading_error_placeholder: 'ğŸ è·å–å¤±è´¥...' # åŠ è½½ä¸€è¨€å¤±è´¥æ—¶çš„å ä½ç¬¦
        category: # ä¸€è¨€å¥å­ç±»å‹ï¼ˆå¯é€‰ï¼‰ï¼Œä¸é…ç½®çš„è¯éšæœºè·å–ï¼Œè¯¦è§ https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
  - name: archive #settings: widgetAchive
    enable: true
    options:
      widgetAchive: #æ–‡ç« å½’æ¡£ç»„ä»¶
        archive_type: 'year' #æŒ‰æœˆå±•ç¤ºè¿˜æ˜¯æŒ‰å¹´å±•ç¤º
        show_count: true  #æ˜¯å¦å±•ç¤ºæ•°é‡
  - name: recent_posts
    enable: true
  - name: link #settings: widgetLink
    enable: true
    options:
      widgetLink: #é“¾æ¥ç»„ä»¶
        - title: ç³–ç³–ç¬¬ä¸€å¯çˆ±
          img: https://cdn.tangyuxian.com/PicGoImages/202304272004917.jpg
          link : https://tangyuxian.com/
# æ‰©å±•æŒ‚ä»¶
pendant:
  enable: true
  options:
    - clock #æ—¶é’Ÿ
    - qweather #å¤©æ°”
copyTip: "è‘—ä½œæƒå½’ä½œè€…æ‰€æœ‰ã€‚\nå•†ä¸šè½¬è½½è¯·è”ç³»ä½œè€…è·å¾—æˆæƒï¼Œéå•†ä¸šè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚\næ¥æºï¼š%url" # è‡ªå®šä¹‰å¤åˆ¶ç‰ˆæƒæ–‡æ¡ˆ,ä½¿ç”¨ %url ä»£æ›¿å½“å‰é¡µé¢URL, ä¿®æ”¹ä¸ºfalseç¦ç”¨

slotHead: |
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-1Z7TFL96ZH"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-1Z7TFL96ZH');
  </script>
slotFooter: |


# è‡ªå®šä¹‰ä¾§è¾¹æ å°¾éƒ¨å†…å®¹
slotSidebar: |
  <br><a target="_blank" href="https://beian.miit.gov.cn/">è¾½ICPå¤‡2021002341å·</a>
  <div style="font-size: 12px">
     <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>
     æœ¬ç«™æ€»è®¿é—®é‡  <a id="busuanzi_value_site_pv"></a> æ¬¡<br />
     æœ¬ç«™è®¿å®¢æ•°<a id="busuanzi_value_site_uv"></a>äººæ¬¡
  </div>

# è¯„è®ºæ¡†æ’æ§½
slotComment: |
  <div class="valine"></div>
  <script src='https://lib.baomitu.com/valine/1.3.9/Valine.min.js'></script>
  <script>
    new Valine({
        el: '.valine',
        appId: 'r5zxC0st0DDjPA9auXzMV7HY-gzGzoHsz',
        appKey: '3bqCsovpyfTPHUzTHovd3V3V'
    })
  </script>

slotCopyright: |
  <strong>ç‰ˆæƒå£°æ˜ï¼š</strong>æœ¬æ–‡é‡‡ç”¨ <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> åè®®è¿›è¡Œè®¸å¯

slotArticleEnd: | 
